[package]
name = "engine_bullet_sys"
version = "0.1.0"
authors = ["Jan Katzer <code.katzer@gmail.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
cc = "1.0.54"
glob = "0.3.0"
bindgen = "0.54.0"
